Let's familiarize with some types of variables.

In [3]:
a=3; print(a)
print('7.341')
print('abc'+'zy')


3
7.341
abczy


The types that we looked at here above are called "integer", "float" and "string".

And now let's make test some mathematical operations with these different types:

In [15]:
2+2

4

In [7]:
2+2.0

4.0

In [8]:
3**3

27

In [6]:
3**5.0

243.0

In [10]:
6/2

3.0

In [11]:
2/6

0.3333333333333333

In [12]:
'a'+'b'

'ab'

In [ ]:
Play with the formulas on top, to become accostomed to the #You can also change the type of each variable:
int('32')
str(3.2)
int(5.99)
int('5.99') #this will give you error

In [7]:
int(float('5.99')) #this works

5

In [14]:
#function example
def printSomething(whateverIwant):
    print(whateverIwant)
printSomething('I like Geodynamics')
printSomething(str(4)+'a')




I like Geodynamics
4a


In [2]:
#factorial calculation using recursive function
def fact(n):
    if n==1:
        return 1
    else:
        return n*fact(n-1)
print(fact(20))

2432902008176640000


In [1]:
def doublePrint(a):
    print(a+a)
doublePrint(2)
doublePrint('ciao')

4
ciaociao


In [ ]:
#Conditional statements
def congratulateGrade(grade):
    if grade=='F':
        print('Mmm, something went wrong')
    elif grade=='D':
        print('Not the best performance')
    elif grade=='C':
        print('It is ok!')
    elif grade=='B':
        print('Very good!')
    elif grade=='A':
        print('Fantastic!')

for x in [6,'ciao',8*8,congratulateGrade]: 
    print(x)

In [25]:
a=5; b=5
if a:
    print(10)
b=0
if b:
    print(0)

10


In [20]:
print(5==5)
print(5==6)


True
False


In [55]:
import numpy as np
a=range(10); 
b=np.arange(10); 
c=b+1; 
d=np.arange(1,11,3); 
e=b**c; 
for x in (a,b,c,d,e):
    print(x)
#print('a=',a,'\n','b=',b,'\n','c=',c,'\n','d=',d,'\n','e=',e)

range(0, 10)
[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]
[         0          1          8         81       1024      15625
     279936    5764801  134217728 3486784401]


In [6]:
sum=0
for x in range(101):
    sum+=x
print(sum)

5050


In [4]:
myRange=(5,98,3.0)
for x in myRange:
    print(x.dtype,x)

AttributeError: 'int' object has no attribute 'dtype'

In [6]:
from numpy import *
a=arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
import numpy as np
b=np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
